---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
#| include: false
library(tidyverse)
library(here)
library(snakecase)
library(fs)
library(stringr)
library(lubridate)
source(here("R/functions.R"))
cgm_data <- here("data-raw/dime/cgm") |>
  import_csv_files() |>
  get_participant_id()
sleep_data <- here("data-raw/dime/sleep") |>
  import_csv_files() |>
  get_participant_id() |>
  rename(datetime = date)
```

```{r}
# Code chunk
```

## Importing CGM data

```{r}
cgm_101 <- here("data-raw/dime/cgm/101.csv") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```
## Exercise: Import 101's sleep data

```{r}
sleep_101 <- here("data-raw/dime/sleep/101.csv") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 120
  )
sleep_101
```

## Making a function that adds numbers

```{r}
#' Add two numbers together
#'
#' @param num1 A number
#' @param num2 A number
#'
#' @returns Returns the sum of the number
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}

add_numbers(1, 2)
```

## Import 101´s cgm data with a function

```{r}
#' Import one participants cgm
#'
#' @param file_path Path to file
#'
#' @returns Returns a data frame
#'
import_cgm <- function(file_path) {
  cgm <- file_path %>%
    readr::read_csv(
      show_col_types = FALSE,
      name_repair = snakecase::to_snake_case,
      n_max = 100
    )
  return(cgm)
}

here("data-raw/dime/cgm/101.csv") %>%
  import_cgm()

here("data-raw/dime/cgm/102.csv") %>%
  import_cgm()
```
## Exercise to make function to import sleep data

```{r}
#' Function exercise on Sleep data
#'
#' @param file_path Path to file
#'
#' @returns returns to a data frame
#'
import_sleep <- function(file_path) {
  sleep <- file_path %>%
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 120
    )
  return(sleep)
}
here("data-raw/dime/sleep/101.csv") %>%
  import_sleep()

here("data-raw/dime/sleep/102.csv") %>%
  import_sleep()
```

## Import DIME data function

```{r}
```


```{r}
here("data-raw/dime/cgm/101.csv") %>%
  import_dime()

here("data-raw/dime/sleep/101.csv") %>%
  import_dime()
```
## Exercise: Convert map to function and use on sleep.

```{r}
here("data-raw/dime/cgm/") |>
  import_csv_files()
here("data-raw/dime/sleep/") |>
  import_csv_files()
```

## Using regex for ID extraction

```{r}
```

```{r}
```
```{r}
# CGM data
cgm_data <- here("data-raw/dime/cgm") |>
  import_csv_files() |>
  get_participant_id()

# Sleep data
sleep_data <- here("data-raw/dime/sleep") |>
  import_csv_files() |>
  get_participant_id()
```

## Working with dates 

```{r}
```

```{r}
cgm_data |>
  prepare_dates(device_timestamp)
```

```{r}
cgm_data |>
  prepare_dates(device_timestamp)
sleep_data <- here("data-raw/dime/sleep") |>
  import_csv_files() |>
  get_participant_id() |>
  rename(datetime = date)
```
